parameters:
    database_host: 192.168.1.176
    database_port: 3309
    database_name: ps
    database_user: root
    database_password:
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt